### ISSUE TITLE
Automatically Create Installer

### ISSUE THREAD

**Issue by notatallshaw** [notatallshaw/fall_guys_ping_estimate#24]
I tried using Github Workflows to automatically create an installer, but I couldn't figure out how to:

1. Not have it wrapped up as a zip file
2. Include in the release

This was my yaml so far, clearly needs some fixing:

```yaml
name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        python -m pip .
    - name: build with pyinstaller
      run: |
        pyinstaller --noconsole --onefile run_fgpe.py
    - uses: actions/upload-artifact@v2
      with:
        name: run_fgpe.exe
        path: dist
```
